name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.1.3
  - seaborn=0.13.2
  - pandas=2.2.1
  - pip=23.3.1
  - pandas-profiling=3.0.0
  - pyarrow=14.0.2
  - pip:
      - wandb==0.16.4