name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter=1.0.0
  - seaborn=0.13.2
  - pandas=2.2.1
  - pip=23.3.1
  - pip:
      - wandb==0.16.4
      - ydata-profiling==4.9.0
      - pyarrow==14.0.2