wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.6
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1723535887
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.10.14
      5: 0.17.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
